name: Setup Deco CLI
description: |
  Download Deco CLI and adds it to $PATH.
  Expects to be run downstream of a `build-deco` job.
  See .github/workflows/build-deco.yml.
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: deco
        path: .bin

    - name: Fix permissions
      shell: bash
      run: chmod +x .bin/deco_*/deco*

    - name: Add to $PATH
      shell: bash
      run: |
        dir="$PWD/.bin/deco"

        # Append correct os name.
        case $RUNNER_OS in
        Linux)
          dir="${dir}_linux"
          ;;
        Windows)
          dir="${dir}_windows"
          ;;
        macOS)
          dir="${dir}_darwin"
          ;;
        esac

        # Append correct arch name.
        case $RUNNER_ARCH in
        X86)
          dir="${dir}_386"
          ;;
        X64)
          dir="${dir}_amd64_v1"
          ;;
        ARM)
          dir="${dir}_arm_6"
          ;;
        ARM64)
          dir="${dir}_arm64"
          ;;
        esac

        if [ ! -d "$dir" ]; then
          echo "Directory does not exist: $dir"
          exit 1
        fi

        if [ "$RUNNER_OS" == "Windows" ]; then
          cd $dir
          mv ./deco.exe ./deco
        fi
        

        echo "$dir" >> $GITHUB_PATH
