project_name: deco
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w'
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    # Snapshots should not have a `_vZZZ` suffix.
    # We assume the executable is named `deco` both on developer machines (see README.md) and in GitHub Actions.
    binary: '{{ .ProjectName }}{{ if not .IsSnapshot }}_v{{ .Version }}{{ end }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  draft: true
