name: bricks-pr-manual

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
        type: string

      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment

jobs:
  pull-request-integration-test:
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout eng-dev-ecosystem
        uses: actions/checkout@v3

      - name: Setup Deco CLI
        uses: ./.github/actions/setup-deco-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout bricks repo
        uses: actions/checkout@v3
        with:
          repository: databricks/bricks
          ref: refs/pull/${{ inputs.pull_request_number }}/merge
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/bricks

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.7
          cache: true
          cache-dependency-path: ext/bricks/go.mod

      - name: Download dependencies for bricks
        run: go mod download
        working-directory: ext/bricks

      - name: Run all bricks acceptance tests
        run: deco env test all --name ${{ matrix.env }} --repo bricks
        shell: bash
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'
