name: sdk-go-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

  schedule:
    - cron: '0 6 * * *'

jobs:
  build-deco:
    name: "Build Deco CLI"
    uses: ./.github/workflows/build-deco.yml
    secrets: inherit

  integration-tests-prod:
    needs: [build-deco]

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - azure-prod
          - gcp-acct-prod
          - gcp-prod
          - aws-acct-prod
          - aws-prod

    environment: ${{ matrix.env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deco CLI
        uses: ./.github/actions/setup-deco-cli

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v2
        with:
          repository: databricks/databricks-sdk-go
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: Download dependencies for databricks-sdk-go
        run: go mod download
        working-directory: ext/databricks-sdk-go

      - name: Run tests
        run: deco env test all --name ${{ matrix.env }} --repo databricks-sdk-go
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.env }}-test.log
          path: test.log
