name: sdk-go-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch

  schedule:
    - cron: '0 6 * * *'

jobs:
  integration-tests-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - azure-prod
          - gcp-acct-prod
          - gcp-prod
          - aws-acct-prod
          - aws-prod

    environment: ${{ matrix.env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # This step is only needed while the deco CLI still depends on TF (see #42).
      - name: Checkout terraform-provider-databricks
        uses: actions/checkout@v2
        with:
          repository: databricks/terraform-provider-databricks
          path: ext/terraform-provider-databricks

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v2
        with:
          repository: databricks/databricks-sdk-go
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: Vendor dependencies
        run: |
          if ! go mod vendor; then
            go mod tidy
          fi
          git diff || true
        working-directory: go

      - name: Run tests
        run: go run main.go env test all --name ${{ matrix.env }} --repo databricks-sdk-go
        working-directory: go
