name: sdk-go-pr-manual

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
        type: number

      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build-deco:
    name: "Build Deco CLI"
    uses: ./.github/workflows/build-deco.yml
    secrets: inherit

  integration-tests-pull-request:
    needs: [build-deco]

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deco CLI
        uses: ./.github/actions/setup-deco-cli

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v3
        with:
          repository: databricks/databricks-sdk-go
          ref: refs/pull/${{ inputs.pull_request_number }}/merge
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.7

      - name: Download dependencies for databricks-sdk-go
        run: go mod download
        working-directory: ext/databricks-sdk-go

      - name: Run tests
        run: deco env test all --name ${{ inputs.environment }} --repo databricks-sdk-go
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.environment }}-test.log
          path: test.log
