name: terraform-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  schedule:
    - cron: '0 6 * * *'

jobs:
  integration-tests-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [azure-prod,gcp-prod,aws-acct-prod,aws-prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - run: cd ext && git clone https://github.com/databricks/terraform-provider-databricks

      - name: Expand actions environment secrets to variables
        run: python3 scripts/tfit-env.py ${{ matrix.env }} '${{ toJson(secrets) }}' >> $GITHUB_ENV
      
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go install gotest.tools/gotestsum@latest

      - name: Run provider integration tests
        run: make vendor && bash scripts/it.sh
        working-directory: ext/terraform-provider-databricks
      
      # main summary page of a job run
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: ext/terraform-provider-databricks/junit.xml
        if: always()

      # dedicated page, needs a separate click to view, 
      # like https://github.com/databricks/eng-dev-ecosystem/runs/7214261090
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report for ${{matrix.env}}
          path: ext/terraform-provider-databricks/junit.xml
          reporter: java-junit
        if: always()
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install ghapi
      - run: python3 scripts/release-notes.py >> $GITHUB_STEP_SUMMARY
  completeness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ext && git clone https://github.com/databricks/terraform-provider-databricks
      - run: cd ext && git clone https://${{ secrets.DECO_GITHUB_TOKEN }}:x-oauth-basic@github.com/databricks/docs
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x
      - run: go mod vendor && go run coverage-report/main.go >> $GITHUB_STEP_SUMMARY
        working-directory: go
  