name: terraform-pr-manual

# this workflow is intended for manual extra verification of PRs for Terraform Provider

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
        type: number

      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  pull-request-integration-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v3
        with:
          repository: databricks/databricks-sdk-go
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - name: Checkout terraform-provider-databricks
        uses: actions/checkout@v3
        with:
          repository: databricks/terraform-provider-databricks
          ref: refs/pull/${{ inputs.pull_request_number }}/merge
          path: ext/terraform-provider-databricks

      - name: Make vendor for deco CLI
        run: go mod vendor
        working-directory: go

      - name: Make vendor for Terraform Provider
        run: go mod vendor
        working-directory: ext/terraform-provider-databricks

      - run: go run main.go env test all --name ${{ inputs.environment }} --repo terraform-provider-databricks
        working-directory: go
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.environment }}-test.log
          path: go/test.log
