name: terraform-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  schedule:
    - cron: '0 9 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [azure,gcp]
    environment: ${{ matrix.env }}-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - run: cd ext && git clone https://github.com/databricks/terraform-provider-databricks && cd terraform-provider-databricks && git checkout parallel

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go get gotest.tools/gotestsum

      - run: cd ext/terraform-provider-databricks && make vendor
      
      - run: cd ext/terraform-provider-databricks && bash scripts/it.sh
        env:
          CLOUD_ENV: ${{ matrix.env }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      
      # main summary page of a job run
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: ext/terraform-provider-databricks/junit.xml
        if: always()

      # dedicated page, needs a separate click to view, 
      # like https://github.com/databricks/eng-dev-ecosystem/runs/7214261090
      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report for ${{matrix.env}}
          path: ext/terraform-provider-databricks/junit.xml
          reporter: java-junit
        if: always()
