name: terraform-fmt

on:
  push:
    branches:
      - master
    paths:
      - 'ops/**'
  pull_request:
    paths:
      - 'ops/**'

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run terraform fmt
        run: terraform fmt -recursive -check
        working-directory: ops
