name: terraform-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  schedule:
    - cron: '0 6 * * *'

jobs:
  integration-tests-prod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [azure-prod,gcp-prod,aws-acct-prod,aws-prod,gcp-acct-prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v2
        with:
          repository: databricks/databricks-sdk-go
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - name: Checkout terraform-provider-databricks
        uses: actions/checkout@v2
        with:
          repository: databricks/terraform-provider-databricks
          path: ext/terraform-provider-databricks

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: Make vendor for deco CLI
        run: go mod vendor
        working-directory: go

      - name: Make vendor for Terraform Provider
        run: go mod vendor
        working-directory: ext/terraform-provider-databricks

      - run: go run main.go env test all --name ${{ matrix.env }} --repo terraform-provider-databricks
        working-directory: go
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout databricks-sdk-go
        uses: actions/checkout@v2
        with:
          repository: databricks/databricks-sdk-go
          token: ${{ secrets.DECO_GITHUB_TOKEN }}
          path: ext/databricks-sdk-go

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18.x

      - name: Make vendor for deco CLI
        run: go mod vendor
        working-directory: go

      - run: go run main.go gh release-notes -r terraform-provider-databricks --head master >> $GITHUB_STEP_SUMMARY
        working-directory: go
        env:
          GITHUB_TOKEN: ${{ secrets.DECO_GITHUB_TOKEN }}

### Disabling completeness check before the bot user is added as reader to docs repo      
  # completeness:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: cd ext && git clone https://${{ secrets.DECO_GITHUB_TOKEN }}:x-oauth-basic@github.com/databricks/docs
  #     - name: Checkout databricks-sdk-go
  #       uses: actions/checkout@v2
  #       with:
  #         repository: databricks/databricks-sdk-go
  #         token: ${{ secrets.DECO_GITHUB_TOKEN }}
  #         path: ext/databricks-sdk-go

  #     - name: Checkout terraform-provider-databricks
  #       uses: actions/checkout@v2
  #       with:
  #         repository: databricks/terraform-provider-databricks
  #         path: ext/terraform-provider-databricks

  #     - uses: actions/setup-go@v1
  #       with:
  #         go-version: 1.18.x

  #     - run: go mod vendor
  #       working-directory: go

  #     - run: go run main.go tf cov >> $GITHUB_STEP_SUMMARY
  #       working-directory: go
  