name: terraform-pr-manual

# this workflow is intended for manual extra verification of PRs for Terraform Provider

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: true
        type: string

      environment:
        description: 'Environment to run tests against'
        required: true
        type: environment

jobs:
  pull-request-integration-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deco CLI
        uses: ./.github/actions/setup-deco-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout terraform-provider-databricks
        uses: actions/checkout@v3
        with:
          repository: databricks/terraform-provider-databricks
          ref: refs/pull/${{ inputs.pull_request_number }}/merge
          path: ext/terraform-provider-databricks

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.6
          cache: true
          cache-dependency-path: ext/terraform-provider-databricks/go.sum

      - name: Make vendor for Terraform Provider
        run: go mod vendor
        working-directory: ext/terraform-provider-databricks

      - name: Run tests
        run: deco env test all --name ${{ inputs.environment }} --repo terraform-provider-databricks
        env:
          GITHUB_SECRETS_JSON: '${{ toJson(secrets) }}'

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ${{ inputs.environment }}-test.log
          path: test.log
