name: terraform-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  schedule:
    - cron: '0 9 * * *'

jobs:
  nightly:
    runs-on: ubuntu-latest
    environment: azure-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow
      
      - run: cd ext && git clone https://github.com/databricks/terraform-provider-databricks

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go get gotest.tools/gotestsum
          go install honnef.co/go/tools/cmd/staticcheck@v0.2.2

      - run: cd ext/terraform-provider-databricks && make vendor
      
      - run: cd ext/terraform-provider-databricks && bash scripts/it.sh
        env:
          CLOUD_ENV: azure
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: ext/terraform-provider-databricks/junit.xml
        if: always()
