name: terraform-nightly

on:
  workflow_dispatch:
    # manual workflow testing
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  schedule:
    - cron: '0 9 * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: azure-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: cd ext && git clone https://github.com/databricks/terraform-provider-databricks

      - uses: actions/setup-go@v1
        with:
          go-version: 1.16.x

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go get gotest.tools/gotestsum

      - run: cd ext/terraform-provider-databricks && make vendor
      
      - run: cd ext/terraform-provider-databricks && bash scripts/it.sh
        env:
          CLOUD_ENV: azure
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration tests
          path: ext/terraform-provider-databricks/junit.xml
          reporter: java-junit
